#ifndef VERSION_HPP
#define VERSION_HPP

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 1
#define APP_VERSION_SUFFIX "alpha"

// Строковое представление версии
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define APP_VERSION_STRING \
TOSTRING(APP_VERSION_MAJOR) "." \
TOSTRING(APP_VERSION_MINOR) "." \
TOSTRING(APP_VERSION_PATCH) "-" \
APP_VERSION_SUFFIX

#endif // VERSION_HPP