name: CMake + Qt 6.5 (Linux GCC)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QT_VERSION: 6.5.3
      QT_ARCH: gcc_64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4

    - name: Install Build Tools
      run: |
        sudo apt-get install -y \
          g++-12 \
          cmake \
          ninja-build \
          ccache
        
        # Создаем симлинки для совместимости
        sudo ln -sf /usr/bin/g++-12 /usr/bin/g++
        sudo ln -sf /usr/bin/gcc-12 /usr/bin/gcc

    - name: Configure CMake
      shell: bash
      run: |
        echo "Using CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
        echo "Using Qt6_DIR: $Qt6_DIR"
        
        cmake -B build \
          -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \
          -DQt6_DIR="$Qt6_DIR" \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -S .

    - name: Build
      run: cmake --build build --config Release --parallel 4

    - name: Run Tests
      working-directory: ./build
      run: ctest --output-on-failure
