name: CMake + Qt 6.5 (Linux GCC)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QT_VERSION: 6.5.0
      QT_ARCH: gcc_64

    steps:
    - uses: actions/checkout@v4

    - name: Setup Qt ${{ env.QT_VERSION }}
      shell: bash
      run: |
        # Удаляем возможные конфликтующие версии Qt
        sudo apt-get remove '^qt6-.*' -y
        
        # Устанавливаем необходимые системные зависимости
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          libgl1-mesa-dev \
          libxkbcommon-x11-0
        
        # Устанавливаем aqtinstall
        pip install aqtinstall
        
        # Устанавливаем Qt
        aqt install-qt linux desktop ${{ env.QT_VERSION }} ${{ env.QT_ARCH }}
        
        # Устанавливаем дополнительные модули (если нужны)
        # aqt install-tool linux desktop tools_ifw
        
        # Настраиваем переменные окружения
        QT_PATH="$HOME/Qt/${{ env.QT_VERSION }}/${{ env.QT_ARCH }}"
        echo "QT_DIR=$QT_PATH" >> $GITHUB_ENV
        echo "PATH=$QT_PATH/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$QT_PATH/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Install Build Tools
      run: |
        sudo apt-get install -y \
          g++ \
          cmake \
          make \
          ninja-build

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B build \
          -DCMAKE_PREFIX_PATH="$QT_DIR" \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -S .

    - name: Build
      run: cmake --build build --config Release --parallel 4

    - name: Run Tests
      working-directory: ./build
      run: ctest --output-on-failure
