name: CMake + Qt 6.5 (Linux GCC)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Устанавливаем Qt 6.5.0 с корректными модулями
    - name: Install Qt 6.5.0
      shell: bash
      run: |
        sudo apt-get remove '^qt6-.*' -y
        sudo apt-get install -y python3-pip
        pip install aqtinstall
        # Сначала проверяем доступные модули
        aqt list-qt linux desktop --modules 6.5.0 gcc_64
        # Устанавливаем только существующие модули
        aqt install-qt linux desktop 6.5.0 gcc_64 -m qtbase qt5compat qtdeclarative
        echo "Qt6_DIR=$HOME/Qt/6.5.0/gcc_64/lib/cmake/Qt6" >> $GITHUB_ENV

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make ninja-build

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B build \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt6_DIR="$Qt6_DIR" \
          -S .

    - name: Build
      run: cmake --build build --config Release --parallel 4

    - name: Run Tests
      working-directory: ./build
      run: ctest --output-on-failure
